security:
  oauth2:
    client:
      clientId: 490520596563388
      clientSecret: 5df01c8daa39cc14ef31622daa4effcf
      accessTokenUri: https://graph.facebook.com/oauth/access_token
      userAuthorizationUri: https://www.facebook.com/dialog/oauth
      tokenName: oauth_token
      authenticationScheme: query
      clientAuthenticationScheme: form
    resource:
      userInfoUri: https://graph.facebook.com/me